### ISSUE TITLE
Evaluate https://github.com/spf13/cobra

### ISSUE THREAD

**Issue by andreaturli** [brooklyncentral/brooklyn-cli#1]
That's the tool used by many successful go based project, like docker or kubernetes. Maybe it can hel us.

**Comment by m4rkmckenna** [comment]
:+1

**Comment by googlielmo** [comment]
Cool :)

**Comment by lloyddave** [comment]
Thanks Andrea; Cobra looks very powerful!  We'll have to compare with https://github.com/codegangsta/cli that is used by the original brooklyn-cli.

**Comment by andreaturli** [comment]
I've also found https://github.com/go-swagger/go-swagger today, does it look useful ?

**Comment by geomacy** [comment]
hi Andrea, go-swagger does look like an excellent tool, and for a green-field project I think it would be a clear choice.  My 2¢ though is that, as the current implementation of the tool has the API built in, I'm not sure that moving to go-swagger would be a worthwhile investment of time.  It is something that would be worth bearing in mind for future use, perhaps if there's a significant API revision at some stage.

**Comment by andreaturli** [comment]
@geomacy, makes sense, it was just my little contribution to this interesting project. :)
